server:
  port: 8090
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: 192.168.100.14
jwt:
  secret: NT1JszmA4kcebWfEo/HJr16yXNT1HI1Ri/SZJV4GqpQ=
  expiration: 86400000
spring:
  cloud:
    gateway:
      routes:
        - id: servicio-envio-proposito
          uri:  lb://servicio-envio-proposito
          predicates:
            - Path=/api/envio/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter
        - id: servicio-consulta-pro
          uri:  lb://servicio-consulta-pro
          predicates:
            - Path=/api/pro/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter
        - id: servicio-courier
          uri:  lb://servicio-courier
          predicates:
            - Path=/api/courier/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter                
        - id: servicio-seguridades
          uri:  lb://servicio-seguridades
          predicates:
            - Path=/api/seguridades/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter
        - id: servicio-sucursales
          uri:  lb://servicio-sucursales
          predicates:
            - Path=/api/sucursales/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter
        - id: servicio-entidad-catalogo
          uri:  lb://servicio-entidad-catalogo
          predicates:
            - Path=/api/entidad-cat/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter
        - id: servicio-ventas
          uri:  lb://servicio-ventas
          predicates:
            - Path=/api/ventas/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter
        - id: servicio-tarifas
          uri:  lb://servicio-tarifas
          predicates:
            - Path=/api/tarifas/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter
        - id: servicio-oauth
          uri: lb://servicio-oauth
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1            